spring:
  application:
    name: 'forex-app'
  main:
    banner-mode: 'off'
server:
  port: ${PORT:9000}
  servlet:
    context-path: '/forex-app'
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-server:8761/eureka}